[Task]: Tratar hook use-apps
uxshop/storefront-react pull request #36
Opened 2022-11-30 12:59 UTC by kevenssousa

## Changes
- Adiciona trycatch para retornar um objeto de erro

2022-11-30 13:18 UTC, simaomeyrerdooca requested changes

2022-11-30 13:18 UTC, simaomeyrerdooca commented on src/hooks/use-apps.tsx
>    useEffect(() => {
vamos testar a chamada da função getById diretamente, algo parecido com
`const apps = useApps()`
`const result = apps.getById({id: algumId})`

Isso para evitar a questão de retornarmos `undefined` na primeira chamada do hoook

2022-12-01 14:29 UTC, diovaniBelleboni approved these changes

2022-12-01 18:34 UTC, simaomeyrerdooca approved these changes

2022-12-02 12:32 UTC, merged