[Task] Tratar erro no Hook use-landing-pages
uxshop/storefront-react pull request #49
Opened 2022-12-02 14:15 UTC by kevenssousa

2022-12-02 14:32 UTC, simaomeyrerdooca commented
Falta documentação

2022-12-05 17:01 UTC, simaomeyrerdooca approved these changes

2022-12-06 11:36 UTC, antonydosreis approved these changes

2022-12-06 11:55 UTC, diovaniBelleboni approved these changes

2022-12-06 12:59 UTC, antonydosreis requested changes

2022-12-06 12:59 UTC, antonydosreis commented on src/hooks/use-landing-pages.tsx
> +  function getOne({ id, slug }: LandingPagesHooksParams, fields?: LandingPageFields[]) {
parâmetros redundantes

2022-12-06 17:41 UTC, merged