[Task] Tratar erro no Hook use-menus
uxshop/storefront-react pull request #50
Opened 2022-12-02 14:49 UTC by kevenssousa

## Changes
Tratar o erro nas buscas da API retornando um objeto com erro ou data.

2022-12-02 16:59 UTC, simaomeyrerdooca approved these changes

2022-12-05 17:02 UTC, simaomeyrerdooca approved these changes

2022-12-06 11:34 UTC, antonydosreis approved these changes

2022-12-06 11:56 UTC, diovaniBelleboni approved these changes

2022-12-06 12:57 UTC, antonydosreis requested changes

2022-12-06 12:57 UTC, antonydosreis commented on src/hooks/use-menus.tsx
> +  function getOneById(id: string, fields?: MenuFields[]) {
parâmetros redundantes

2022-12-06 12:57 UTC, antonydosreis commented on src/hooks/use-menus.tsx
> +  function getList(fields?: MenuFields[]) {
parâmetros redundantes

2022-12-06 17:43 UTC, merged