[Task] Tratar erro no Hook use-scripts
uxshop/storefront-react pull request #54
Opened 2022-12-02 15:10 UTC by kevenssousa

## Changes
- implementa logica que retorna data e erro do hook useScripts

2022-12-02 18:18 UTC, simaomeyrerdooca commented on src/hooks/use-scripts.tsx
> +  function getScriptsByFilter({ page, location }: ScriptsHookParam, fields?: Array<ScriptFields>) {
podemos usar `ScriptFields[]` no type de fields

2022-12-02 18:18 UTC, simaomeyrerdooca commented on src/hooks/use-scripts.tsx
> +  function getAllScripts(fields?: Array<ScriptFields>) {
podemos usar `ScriptFields[]` no type de fields

2022-12-05 17:08 UTC, simaomeyrerdooca approved these changes

2022-12-06 11:29 UTC, antonydosreis approved these changes

2022-12-06 12:16 UTC, diovaniBelleboni approved these changes

2022-12-06 12:54 UTC, antonydosreis requested changes

2022-12-06 12:54 UTC, antonydosreis commented on src/hooks/use-pages.tsx
> +  async function getOne({ id, slug }: PageHookParams, fields?: PageFields[]) {
parâmetros redundantes

2022-12-06 12:54 UTC, antonydosreis commented on src/hooks/use-pages.tsx
> +  async function getList(fields?: PageFields[]) {
parâmetros redundantes

2022-12-06 12:54 UTC, antonydosreis commented on src/hooks/use-scripts.tsx
> +  function getScriptsByFilter({ page, location }: ScriptsHookParam, fields?: ScriptFields[]) {
parâmetros redundantes

2022-12-06 12:54 UTC, antonydosreis commented on src/hooks/use-scripts.tsx
> +  function getAllScripts(fields?: ScriptFields[]) {
parâmetros redundantes

2022-12-06 16:36 UTC, antonydosreis approved these changes

2022-12-06 17:49 UTC, merged