[Task] Tratar erro no Hook use-settings
uxshop/storefront-react pull request #56
Opened 2022-12-02 15:29 UTC by kevenssousa

# Changes
Tratar o erro nas buscas da API retornando um objeto com erro ou data.

2022-12-02 18:53 UTC, simaomeyrerdooca approved these changes

2022-12-06 11:25 UTC, antonydosreis approved these changes

2022-12-06 11:26 UTC, antonydosreis requested changes

2022-12-06 11:26 UTC, antonydosreis commented on src/hooks/use-settings.tsx
>      if (data) {
Aqui ficou um `if` sem nada mesmo?

2022-12-06 12:17 UTC, diovaniBelleboni approved these changes

2022-12-06 17:49 UTC, merged