[Task[ Tratar erro no Hook use-sidebar
uxshop/storefront-react pull request #58
Opened 2022-12-02 15:38 UTC by kevenssousa

## Changes
Tratar o erro nas buscas da API retornando um objeto com erro ou data.

2022-12-02 18:54 UTC, simaomeyrerdooca requested changes

2022-12-02 18:54 UTC, simaomeyrerdooca commented on src/hooks/use-sidebar.tsx
> -  useEffect(() => {
Esse hook precisamos avaliar melhor por ter depêndencia no `useEffect`

2022-12-05 17:10 UTC, simaomeyrerdooca approved these changes

2022-12-06 11:23 UTC, antonydosreis approved these changes

2022-12-06 11:23 UTC, antonydosreis commented on src/hooks/use-sidebar.tsx
> +import { useEffect } from 'react'
Pra seguir uma lógica de importação mais padronizada, os imports do react vem primeiro:

1. dependência de terceiros
2. regras de negócio, services, hooks etc..
3. componentes de ui
4. dependências locais, types, mocks etc..

2022-12-06 12:17 UTC, diovaniBelleboni approved these changes

2022-12-06 12:51 UTC, antonydosreis requested changes

2022-12-06 12:51 UTC, antonydosreis commented on src/hooks/use-sidebar.tsx
> +  function get(sidebarFilter?: Array<SidebarHookParams>) {
Parâmetro redundante

2022-12-06 17:51 UTC, merged