[Task] Tratar erro no Hook use-user
uxshop/storefront-react pull request #59
Opened 2022-12-02 19:34 UTC by kevenssousa

## Changes
- Tratar o erro nas buscas da API retornando um objeto com erro ou data.

2022-12-05 17:11 UTC, simaomeyrerdooca approved these changes

2022-12-06 11:21 UTC, antonydosreis requested changes

2022-12-06 11:21 UTC, antonydosreis commented on src/hooks/use-user.tsx
> +    credentials && auth(credentials)
Eu acho pouco legível esse tipo de validação pra que lê o código depois. De qualquer forma não é uma solicitação de correção, so uma sugestão

2022-12-06 11:21 UTC, antonydosreis commented on src/hooks/use-user.tsx
>      if (token) {
Acho que fica mais claro:
`if(!token) return`
`...`

2022-12-06 11:21 UTC, antonydosreis commented on src/hooks/use-user.tsx
> +    UserService.get(token)
Não vai um `await` aqui?

2022-12-06 11:21 UTC, antonydosreis commented on src/hooks/use-user.tsx
> +    UserService.auth(credentials)
Aqui acho que também

2022-12-06 12:18 UTC, diovaniBelleboni approved these changes

2022-12-06 12:50 UTC, antonydosreis requested changes

2022-12-06 12:50 UTC, antonydosreis commented on src/hooks/use-user.tsx
> +  function auth(credentials: LoginCredentials, fields?: UserFields[]): any {
Aqui da pra remover todos os parâmetros dos métodos, o `credencias` vem do escopo da função, e o `fields`, não está sendo usado

2022-12-06 12:50 UTC, antonydosreis commented on src/hooks/use-user.tsx
>    async function get(token: string) {
Aqui o parâmetro é redundante

2022-12-07 12:24 UTC, merged