[feat] Criar wrapper no react dos componentes de LPs
uxshop/storefront-react pull request #65
Opened 2022-12-07 12:29 UTC by vitorbruski

## [feat] Criar wrapper no react dos componentes de LPs

[feat link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront-4?workitem=4621)

### Changes:

adicionado wrappers:
- ux-banners
- ux-carousel
- ux-carousel-item
- ux-showcase
- ux-showcase-item
- ux-testimonials
- ux-text-image
- ux-video

2022-12-07 17:25 UTC, antonydosreis requested changes

2022-12-07 17:25 UTC, antonydosreis commented on src/components/ux/ux-text-image/index.tsx
> +    side: settings.side
Está correto está prop não seguir o padrão `data-...`?

2022-12-07 17:25 UTC, antonydosreis commented on src/components/ux/ux-video/types.ts
> +  url: string
Colocar as props opcionais por último

2022-12-07 17:53 UTC, vitorbruski commented on src/components/ux/ux-text-image/index.tsx
> +    side: settings.side
acredito que sim
no componente a prop é passada apenas como `side`
<img width="239" alt="image" src="https://user-images.githubusercontent.com/57164609/206258065-b32108ef-7090-48d5-ae1e-c1e9d7b0717b.png">

2022-12-07 19:18 UTC, antonydosreis commented on src/components/ux/ux-text-image/index.tsx
> +    side: settings.side
Bem estranha essa quebra de padrão, pode confirmar isso @simaomeyrerdooca?

2022-12-08 04:04 UTC, simaomeyrerdooca commented on src/components/ux/ux-text-image/index.tsx
> +    side: settings.side
de fato é estranha, se trata da posição que vai ficar o conteúdo `left | right` poderia ter um nome mais legível como `data-position` ou algo do tipo e a mesma coisa para o tipo dele, pra isso precisamos mudar nesse projeto e no storefront-components

2022-12-08 04:06 UTC, simaomeyrerdooca requested changes

2022-12-08 04:06 UTC, simaomeyrerdooca commented on src/index.ts
>  export { UxTextImage } from './components/ux-text-image'
o path dos componentes `UxVideo` e `UxTextImage` estão causando erro no build
<img width="980" alt="Captura de Tela 2022-12-08 às 01 00 05" src="https://user-images.githubusercontent.com/91201387/206354050-a283943f-bc8b-444b-8aac-27e26131d5a5.png">

2022-12-08 12:15 UTC, vitorbruski commented on src/components/ux/ux-text-image/index.tsx
> +    side: settings.side
@simaomeyrerdooca essa alteração no `storefront-components` eu posso ir fazendo?

2022-12-08 13:41 UTC, antonydosreis requested changes

2022-12-08 13:41 UTC, antonydosreis commented on src/components/ux/ux-video/types.ts
> +  url: string
Continua com a ordem anterior

2022-12-08 13:41 UTC, simaomeyrerdooca approved these changes

2022-12-08 14:37 UTC, antonydosreis approved these changes

2022-12-08 14:49 UTC, merged