[Feat] Integração de landing pages
uxshop/storefront-react pull request #76
Opened 2022-12-21 01:29 UTC by simaomeyrerdooca

## [Feat] Integração de landing pages

### Changes:
- Criado componente para carregar as landing pages
- Ajuste das props e types incorretos nos componentes ux-banners e ux-video

2022-12-21 10:52 UTC, tiagotermedooca requested changes

2022-12-21 10:52 UTC, tiagotermedooca commented on src/components/ux/index.tsx
> +import { UxBanners } from '../ux/ux-banners'
renomear pasta para landingpage

2022-12-21 10:52 UTC, tiagotermedooca commented on src/components/landing-page/index.tsx
> +export function LandingPage(): JSX.Element {
o componente pode receber mais componentes e o data, são props opcionais

2022-12-21 11:28 UTC, diovaniBelleboni approved these changes

2022-12-22 14:48 UTC, tiagotermedooca approved these changes

2022-12-22 14:48 UTC, merged